### ISSUE TITLE
Have one RetryInterval

### ISSUE THREAD

**Issue by loicbourgois** [scaleway/scaleway-sdk-go#358]
**Problem**

`RetryInterval` is set at the level of a product

It is specified for both 
- https://github.com/scaleway/scaleway-sdk-go/blob/master/api/instance/v1/server_utils.go#L23
- https://github.com/scaleway/scaleway-sdk-go/blob/master/api/baremetal/v1alpha1/server_utils.go#L14

In the CLI, setting `RetryInterval = 0` allows to execute the WaitFor funcs immediately. 

We need to handle it for each product in CLI tests.
- https://github.com/scaleway/scaleway-cli/blob/v2/internal/namespaces/instance/v1/instance_cli_test.go#L14
- same for baremetal once it is implemented

**Proposal**

Maybe we should have a higher variable, either in the SDK or in the CLI, so we don't have to handle `RetryInterval` for the tests of each product.

**Comment by jerome-quere** [comment]
This is not a bad idea but it was design this way in order to be able to set a different RetryTimeout based on the type of resource we wait. Some resource may need a shorter retry time than other. Either way, this may be an overkill feature and we might consider moving it inside the client to avoid global state
